---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/nndscomy/repositories/jsitherapy/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
