deployment:
  tasks:
    - export DEPLOYPATH=/home1/nndscomy/public_html/
    - mkdir -p $DEPLOYPATH  # Ensure the target directory exists
    - |
      if [ -d "images" ]; then
        /bin/cp -R images $DEPLOYPATH
      else
        echo "images directory does not exist!"
      fi
    - |
      if [ -d "docs" ]; then
        /bin/cp -R docs $DEPLOYPATH
      else
        echo "docs directory does not exist!"
      fi
    - |
      if [ -d "scripts" ]; then
        /bin/cp -R scripts $DEPLOYPATH
      else
        echo "scripts directory does not exist!"
      fi
    - |
      if [ -d "css" ]; then
        /bin/cp -R css $DEPLOYPATH
      else
        echo "css directory does not exist!"
      fi
    - |
      if [ -f "index.html" ]; then
        /bin/cp index.html $DEPLOYPATH
      else
        echo "index.html file does not exist!"
      fi
    - |
      if [ -f "services.html" ]; then
        /bin/cp services.html $DEPLOYPATH
      else
        echo "services.html file does not exist!"
      fi
    - |
      if [ -f "about.html" ]; then
        /bin/cp about.html $DEPLOYPATH
      else
        echo "about.html file does not exist!"
      fi
    - |
      if [ -f "contact.html" ]; then
        /bin/cp contact.html $DEPLOYPATH
      else
        echo "contact.html file does not exist!"
      fi
